default:
  trainer: ppo
  batch_size: 1024
  beta: 1e-3
  buffer_size: 10240
  epsilon: 0.15
  gamma: 0.99
  hidden_units: 128
  lambd: 0.95
  learning_rate: 3.0e-4
  max_steps: 5.0e6
  normalize: false
  num_epoch: 4
  num_layers: 2
  time_horizon: 512
  summary_freq: 1000
  use_curiosity: false
  curiosity_strength: 0.01
  curiosity_enc_size: 128
  use_recurrent: false
  memory_size: 128
  sequence_length: 16